
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jayabharathreddys/config_server_property
          clone-on-start: true
management:
  security:
    enabled: false